# Generated by Django 2.1.5 on 2019-02-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upazilla',
            old_name='country',
            new_name='district',
        ),
    ]
