# Generated by Django 2.1.2 on 2019-02-26 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190224_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upazilla',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.district'),
        ),
    ]
